# Generated by Django 5.1 on 2024-11-23 23:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wraps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwrap',
            old_name='title',
            new_name='wrap_type',
        ),
        migrations.RemoveField(
            model_name='userwrap',
            name='content',
        ),
        migrations.AddField(
            model_name='userwrap',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userwrap',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userwrap',
            name='wrap_data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
