# Generated by Django 5.1.2 on 2024-10-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_rename_expires_in_spotifytoken_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifytoken',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='spotifytoken',
            name='expires_in',
            field=models.IntegerField(default=60),
        ),
    ]
